import { useState, useEffect, useCallback } from 'react';
import { supabase } from '@/integrations/supabase/client';
import { useToast } from '@/hooks/use-toast';
import { useAuth } from '@/contexts/AuthContext';
import type { Database } from '@/integrations/supabase/types';

type ClaimRow = Database['public']['Tables']['claims']['Row'];
type ClaimInsert = Database['public']['Tables']['claims']['Insert'];
type ClaimUpdate = Database['public']['Tables']['claims']['Update'];

export interface Claim extends ClaimRow {
  account?: { id: string; account_name: string } | null;
  item?: { id: string; item_code: string; description: string | null } | null;
  filed_by_user?: { id: string; first_name: string | null; last_name: string | null } | null;
}

export type ClaimType = 'damage' | 'loss' | 'shortage' | 'delay' | 'other';
export type ClaimStatus = 'open' | 'investigating' | 'pending_approval' | 'approved' | 'denied' | 'paid' | 'closed';

export interface ClaimFilters {
  status?: ClaimStatus;
  claimType?: ClaimType;
  accountId?: string;
}

export function useClaims(filters?: ClaimFilters) {
  const [claims, setClaims] = useState<Claim[]>([]);
  const [loading, setLoading] = useState(true);
  const { toast } = useToast();
  const { profile } = useAuth();

  const fetchClaims = useCallback(async () => {
    if (!profile?.tenant_id) return;
    
    try {
      setLoading(true);
      let query = supabase
        .from('claims')
        .select(`
          *,
          account:accounts!claims_account_id_fkey(id, account_name),
          item:items!claims_item_id_fkey(id, item_code, description),
          filed_by_user:users!claims_filed_by_fkey(id, first_name, last_name)
        `)
        .eq('tenant_id', profile.tenant_id)
        .is('deleted_at', null)
        .order('created_at', { ascending: false });

      if (filters?.status) {
        query = query.eq('status', filters.status);
      }
      if (filters?.claimType) {
        query = query.eq('claim_type', filters.claimType);
      }
      if (filters?.accountId) {
        query = query.eq('account_id', filters.accountId);
      }

      const { data, error } = await query;

      if (error) throw error;
      setClaims(data || []);
    } catch (error) {
      console.error('Error fetching claims:', error);
      toast({
        variant: 'destructive',
        title: 'Error',
        description: 'Failed to load claims',
      });
    } finally {
      setLoading(false);
    }
  }, [filters?.status, filters?.claimType, filters?.accountId, profile?.tenant_id, toast]);

  useEffect(() => {
    fetchClaims();
  }, [fetchClaims]);

  const createClaim = async (data: Omit<ClaimInsert, 'tenant_id' | 'claim_number'> & { claim_number?: string }) => {
    if (!profile?.tenant_id) throw new Error('No tenant');
    
    // claim_number is auto-generated by trigger, but we need to satisfy TypeScript
    const insertData = { 
      ...data, 
      tenant_id: profile.tenant_id,
      filed_by: profile.id,
      claim_number: data.claim_number || '', // Will be overwritten by trigger
    };
    
    const { data: result, error } = await supabase
      .from('claims')
      .insert([insertData])
      .select()
      .single();

    if (error) throw error;
    
    toast({
      title: 'Claim Filed',
      description: `Claim ${result.claim_number} has been created`,
    });
    
    await fetchClaims();
    return result;
  };

  const updateClaim = async (id: string, data: ClaimUpdate) => {
    const { data: result, error } = await supabase
      .from('claims')
      .update(data)
      .eq('id', id)
      .select()
      .single();

    if (error) throw error;
    await fetchClaims();
    return result;
  };

  const resolveClaim = async (id: string, resolution: {
    status: 'approved' | 'denied' | 'paid' | 'closed';
    approved_amount?: number;
    resolution_notes?: string;
  }) => {
    if (!profile?.id) throw new Error('No user');
    
    const { data: result, error } = await supabase
      .from('claims')
      .update({
        status: resolution.status,
        approved_amount: resolution.approved_amount,
        resolution_notes: resolution.resolution_notes,
        resolved_by: profile.id,
        resolved_at: new Date().toISOString(),
      })
      .eq('id', id)
      .select()
      .single();

    if (error) throw error;
    
    toast({
      title: 'Claim Updated',
      description: `Claim has been ${resolution.status}`,
    });
    
    await fetchClaims();
    return result;
  };

  const deleteClaim = async (id: string) => {
    const { error } = await supabase
      .from('claims')
      .update({ deleted_at: new Date().toISOString() })
      .eq('id', id);

    if (error) throw error;
    await fetchClaims();
  };

  return {
    claims,
    loading,
    refetch: fetchClaims,
    createClaim,
    updateClaim,
    resolveClaim,
    deleteClaim,
  };
}
