// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lxkstlsfxocaswqwlmed.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx4a3N0bHNmeG9jYXN3cXdsbWVkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njg1Mjk1NTQsImV4cCI6MjA4NDEwNTU1NH0.p-X92RJdzgSrfSsVY_qC-Bxnr7hEWhvGj41Lf97RYtE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});